stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# Étape 1 : Build de l'image Docker
build:
  stage: build
  script:
    - docker build -t $IMAGE_TAG .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker push $IMAGE_TAG
  only:
    - main
    - develop

# Étape 2 : Tests automatisés
test:
  stage: test
  image: $IMAGE_TAG
  script:
    - pip install -r requirements_fastapi.txt
    - pytest tests/
  only:
    - main
    - develop

# Étape 3 : Déploiement vers Kubernetes
deploy:
  stage: deploy
  image: bitnami/kubectl:latest
  script:
    - kubectl config set-cluster my-cluster --server=$KUBERNETES_SERVER
    - kubectl config set-credentials gitlab-runner --token=$KUBERNETES_TOKEN
    - kubectl config set-context my-cluster --cluster=my-cluster --namespace=default --user=gitlab-runner
    - kubectl config use-context my-cluster
    - kubectl apply -f deployment.yaml
    - kubectl apply -f service.yaml
  only:
    - main
