stages:
  - build
  - test
  - deploy

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

# Étape 1 : Build de l'image Docker
build:
  stage: build
  image: docker:20.10.24  
  services:
    - docker:20.10.24-dind 
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker build -t $IMAGE_TAG .
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker push $IMAGE_TAG
  only:
    - main
    - develop

# Étape 2 : Tests automatisés
test:
  stage: test
  image: $IMAGE_TAG  
  script:
    - pip install -r requirements_fastapi.txt  
    - pytest /app/tests/  
  only:
    - main
    - develop


# Étape 3 : Déploiement vers Kubernetes
deploy:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  script:
    - echo "$KUBECONFIG" > kubeconfig.yaml
    - kubectl version --client
    - kubectl --kubeconfig=kubeconfig.yaml cluster-info
    - kubectl --kubeconfig=kubeconfig.yaml apply -f deployment.yaml
    - kubectl --kubeconfig=kubeconfig.yaml apply -f service.yaml
  only:
    - main