apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: $IMAGE_TAG  
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: model-volume
          mountPath: /app/ML
      volumes:
      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc