# Utiliser une image de base avec Python
FROM python:3.9-slim

# Définir le répertoire de travail dans le conteneur
WORKDIR /app

# Copier le fichier des dépendances
COPY requirements_fastapi.txt .

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements_fastapi.txt

# Copier le script FastAPI dans le conteneur
COPY Fastapi.py /app/
COPY model_vente_mensuelle.pkl /app/ML/model_vente_mensuelle.pkl
COPY nouvelle_bd.csv /app/Data/nouvelle_bd.csv
COPY nouvelle_bd_2.csv /app/Data/nouvelle_bd_2.csv 

# Exposer le port 8000 pour FastAPI
EXPOSE 8000

# Lancer l'application avec Uvicorn
CMD ["uvicorn", "Fastapi:app", "--host", "0.0.0.0", "--port", "8000"]
